################################################################################
FROM ubuntu:20.04 as builder
ARG deps_dir

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
            build-essential             \
            cmake                       \
            curl                        \
            g++-8                       \
            git                         \
            libcurl4-openssl-dev        \
            libgmp-dev                  \
            libssl-dev                  \
            libusb-1.0-0-dev            \
            llvm-7-dev                  \
            pkg-config                  \
            python3                     \
            zlib1g-dev &&               \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/wax-blockchain
COPY ${deps_dir}/wax-blockchain .
RUN curl -L https://boostorg.jfrog.io/artifactory/main/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar jx && \
    cd boost_1_70_0 &&                                                                                     \
    ./bootstrap.sh --prefix=$HOME/boost1.70 &&                                                             \
    ./b2 --with-iostreams --with-date_time --with-filesystem --with-system                                 \
        --with-program_options --with-chrono --with-test -j$(nproc) install &&                             \
    cd .. &&                                                                                               \
    scripts/install_deps.sh     &&                                                                         \
    scripts/pinned_build.sh deps build $(nproc)
    
ENV EOSIO_ROOT=/tmp/wax-blockchain
ENV PATH="/tmp/wax-blockchain/bin:${PATH}"
ENV LEAP_BUILD_PATH=/tmp/wax-blockchain/build