################################################################################
FROM ubuntu:22.04 as builder
ARG deps_dir

RUN apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get -y install \
        build-essential \
        cmake \
        curl \
        git \
        libboost-all-dev \
        libcurl4-openssl-dev \
        libgmp-dev \
        libssl-dev \
        llvm-11-dev \
        python3-numpy && \
        rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/wax-blockchain
COPY ${deps_dir}/wax-blockchain .
RUN mkdir build && cd build &&                                                                             \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 .. &&                            \
    make -j $(nproc) package
    
ENV EOSIO_ROOT=/tmp/wax-blockchain
ENV PATH="/tmp/wax-blockchain/bin:${PATH}"
ENV LEAP_BUILD_PATH=/tmp/wax-blockchain/build