################################################################################
ARG WAX_VERSION
FROM waxteam/waxnode-dev:$WAX_VERSION

ARG deps_dir=.

RUN apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get -y install \
        build-essential             \
        clang                       \
        clang-tidy                  \
        cmake                       \
        git                         \
        libxml2-dev                 \
        opam ocaml-interp           \
        python3                    \
        python3-pip                 \
        time &&                     \
    rm -rf /var/lib/apt/lists/* &&  \
    python3 -m pip install pygments

WORKDIR /tmp/wax-cdt
COPY ${deps_dir}/cdt . 
ENV leap_DIR=$LEAP_BUILD_PATH/lib/cmake/leap
RUN mkdir build &&      \
    cd build &&         \
    cmake -DBOOST_ROOT=$HOME/boost1.70 .. &&         \
    make -j $(nproc) &&         \
    make install
ENV PATH="/usr/local/cdt/bin:${PATH}"
ENV CDT_BUILD_PATH=/tmp/wax-cdt/build