################################################################################
FROM ubuntu:22.04 as builder  
ARG deps_dir

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
            build-essential             \
            cmake                       \
            curl                        \
            file                        \
            git                         \
            libcurl4-openssl-dev        \
            libgmp-dev                  \
            libssl-dev                  \
            libusb-1.0-0-dev            \
            llvm-11-dev                 \
            pkg-config                  \
            python3                     \
            zlib1g-dev &&               \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2 | tar jx && \
    cd boost_1_79_0 &&                                                                                     \
    ./bootstrap.sh --prefix=$HOME/boost1.79 &&                                                             \
    ./b2 --with-iostreams --with-date_time --with-filesystem --with-system                                 \
        --with-program_options --with-chrono --with-test -j$(nproc) install

WORKDIR /tmp/wax-blockchain
COPY ${deps_dir}/wax-blockchain .
RUN mkdir -p build
WORKDIR /tmp/wax-blockchain/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 ..
RUN make -j $(nproc) package
    
ENV EOSIO_ROOT=/tmp/wax-blockchain
ENV PATH="/tmp/wax-blockchain/build/bin:${PATH}"
ENV LEAP_BUILD_PATH=/tmp/wax-blockchain/build